version: '3.1'

services:

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: dell
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ./docker/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./docker/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"